### ISSUE TITLE
Server crashed (Chrome bitness 32!==64)

### ISSUE THREAD

**Issue by tgoyer** [httptoolkit/feedback#46]
Hi!

I am just trying out your tool.  It installed correctly, but when it launches, I get the following dialog:

**HTTP Toolkit hit an error**
Server crashed with 'Error: Conflict on chrome.bitness: 32 !== 64' (1).
Please file an issue at github.com/httptoolkit/feedback.

It will then restart and attempt again and crash again a few more times.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by tgoyer** [comment]
The only thing that would be unusual about this machine is that it's a virtual Windows image.

Here is the debug you requested:
```
C:\>npx win-detect-browsers --debug
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ HKLM\Software\Wow6432Node\Google\Update /v LastInstallerSuccessLaunchCmdLine +0ms
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe +6ms
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ HKLM\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe +2ms
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ HKLM\Software\Wow6432Node\Clients\StartMenuInternet\Google Chrome\shell\open\command +1ms
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ HKLM\Software\Clients\StartMenuInternet\Google Chrome\shell\open\command +2ms
  win-detect-browsers Found chrome (stable) (32):
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ Software\Wow6432Node\Google\Update\ClientState\{8A69D345-D564-463C-AFF1-A69D9E530F96}\LastInstallerSuccessLaunchCmdLine +2ms
  win-detect-browsers Found ie:
  win-detect-browsers   - C:\Program Files\Internet Explorer\iexplore.exe
  win-detect-browsers   @ HKLM\Software\Wow6432Node\Clients\StartMenuInternet\iexplore.exe\shell\open\command +3ms
  win-detect-browsers Found ie:
  win-detect-browsers   - C:\Program Files\Internet Explorer\iexplore.exe
  win-detect-browsers   @ HKLM\Software\Clients\StartMenuInternet\iexplore.exe\shell\open\command +4ms
  win-detect-browsers Found chrome (stable):
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ Software\Classes\ChromeHTML\shell\open\command +3ms
  win-detect-browsers Found chrome:
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ default location +2ms
  win-detect-browsers Found ie:
  win-detect-browsers   - C:\Program Files (x86)\Internet Explorer\iexplore.exe
  win-detect-browsers   @ default location +2ms
  win-detect-browsers Found ie:
  win-detect-browsers   - C:\Program Files\Internet Explorer\iexplore.exe
  win-detect-browsers   @ default location +4ms
  win-detect-browsers Found chrome (stable) (64):
  win-detect-browsers   - C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  win-detect-browsers   @ Software\Wow6432Node\Google\Update\ClientState\{4DC8B4CA-1BDA-483E-B5FA-D3C12E15B62D}\UninstallString +6ms
c:\temp\npm_cache\_npx\17320\node_modules\win-detect-browsers\lib\finder.js:218
            throw new Error(`Conflict on ${this.name}.${k}: ${v1} !== ${v2}`)
            ^

Error: Conflict on chrome.bitness: 32 !== 64
    at Finder.found (c:\temp\npm_cache\_npx\17320\node_modules\win-detect-browsers\lib\finder.js:218:19)
    at fs.access (c:\temp\npm_cache\_npx\17320\node_modules\win-detect-browsers\lib\chrome\find-update-clients.js:75:25)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by pimterry** [comment]
I managed to hunt this down & fix it in win-detect-browsers (https://github.com/vweevers/win-detect-browsers/pull/61) and that was released today in the latest HTTP Toolkit. These Chrome conflicts on Windows should be a thing of the past.

Let me know if you hit any other issues. Thanks for the report!
